# Generated by Django 4.1.3 on 2023-07-13 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0002_alter_uploadfiles_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
